Add missing "this." in page_loader.py
The absence of "this." leads to the following error:

Traceback (most recent call last):
  File "export.py", line 28, in <module>
    loader.download(books)
  File "LivelibExport/page_loader.py", line 39, in download
    if this.try_download_book_page(book):
  File "LivelibExport/page_loader.py", line 30, in try_download_book_page
    cache.save(book.id, page)
NameError: name 'cache' is not defined